<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="it207.css" type="text/css"/>
    </head>
    <body>
		<p>
		<a href="https://oai.gmu.edu/mason-honor-code/" class="copyright_tag">Copyright Content</a>
		</p>
		
    </body>
</html>