<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="it207.css" type="text/css"/>
</head>
<body>

	<a href="https://helios.vse.gmu.edu/~skhan204/IT207/">Home </a> <br/>
	
	<h4> Lab Assignments</h4>
	<ul class="menuitems">
		<li>
			<a href="https://helios.vse.gmu.edu/~skhan204/IT207/LAB1/">Assignment 1</a> <br/>
		</li>
		<li>
			<a href="https://helios.vse.gmu.edu/~skhan204/IT207/LAB2/">Assignment 2</a> <br/>
		</li>
		<li>
			<a href="https://helios.vse.gmu.edu/~skhan204/IT207/LAB3/">Assignment 3<br/>
		</li>
		<li>
			<a href="https://helios.vse.gmu.edu/~skhan204/IT207/LAB4/">Assignment 4</a> <br/>
		</li>
	</ul>
	
	<h4>Lab Practicum</h4>
	<ul class="menuitems">
		<li>
			<a href="https://helios.vse.gmu.edu/~skhan204/IT207/LABP1/">Practicum 1</a> <br/>
		</li>
		<li>
			<a href="LABP2/practicum2.html">Practicum 2</a> <br/>
		</li>
	</ul>
	
	

</body>
</html>
